package me.capitainecat0.multicommands.utils;

import static me.capitainecat0.multicommands.utils.MessengerUtils.*;

public enum Messenger {
    PLUGIN_PREFIX(MessengerUtils.lang("plugin_prefix")),
    HELP_AFK(MessengerUtils.lang("help_afk")),
    HELP_ALERT(MessengerUtils.lang("help_alert")),
    HELP_ANVIL(MessengerUtils.lang("help_anvil")),
    HELP_BAN(MessengerUtils.lang("help_ban")),
    HELP_BROADCAST(MessengerUtils.lang("help_broadcast")),
    HELP_CLEARINV(MessengerUtils.lang("help_clear")),
    HELP_CRAFT(MessengerUtils.lang("help_craft")),
    HELP_COMPASS(MessengerUtils.lang("help_compass")),
    HELP_ECONOMY(MessengerUtils.lang("help_economy")),
    HELP_ENDERCHEST(MessengerUtils.lang("help_enderchest")),
    HELP_FEED(MessengerUtils.lang("help_feed")),
    HELP_FLY(MessengerUtils.lang("help_fly")),
    HELP_FREEZE(MessengerUtils.lang("help_freeze")),
    HELP_FURNACE(MessengerUtils.lang("help_furnace")),
    HELP_GAMEMODE(MessengerUtils.lang("help_gamemode")),
    HELP_GIVE(MessengerUtils.lang("help_give")),
    HELP_GOD(MessengerUtils.lang("help_god")),
    HELP_HEAL(MessengerUtils.lang("help_heal")),
    HELP_HELPOP(MessengerUtils.lang("help_helpop")),
    HELP_INVSEE(MessengerUtils.lang("help_invsee")),
    HELP_KICK(MessengerUtils.lang("help_kick")),
    HELP_KICKALL(MessengerUtils.lang("help_kickall")),
    HELP_KILL(MessengerUtils.lang("help_kill")),
    HELP_LEVEL(MessengerUtils.lang("help_level")),
    HELP_LIST(MessengerUtils.lang("help_list")),
    HELP_MUTE(MessengerUtils.lang("help_mute")),
    HELP_MULTICOMMANDS(MessengerUtils.lang("help_multicommands")),
    HELP_MULTIINFOS(MessengerUtils.lang("help_multiinfos")),
    HELP_NICK(MessengerUtils.lang("help_nick")),
    HELP_PING(MessengerUtils.lang("help_ping")),
    HELP_PLUGINS(MessengerUtils.lang("help_plugins")),
    HELP_RELOAD(MessengerUtils.lang("help_reload")),
    HELP_SETSPAWN(MessengerUtils.lang("help_setspawn")),
    HELP_SPAWN(MessengerUtils.lang("help_spawn")),
    HELP_SERVERINFO(MessengerUtils.lang("help_serverinfo")),
    HELP_TELEPORT(MessengerUtils.lang("help_teleport")),
    HELP_TOP(MessengerUtils.lang("help_top")),
    HELP_UNBAN(MessengerUtils.lang("help_unban")),
    HELP_VANISH(MessengerUtils.lang("help_vanish")),
    HELP_WHOIS(MessengerUtils.lang("help_whois")),
    ADMINCHAT(MessengerUtils.lang("admin_chat")),
    ADMINCHAT_PREFIX(MessengerUtils.lang("admin_chat_prefix")),
    STAFFCHAT(MessengerUtils.lang("staff_chat")),
    STAFFCHAT_PREFIX(MessengerUtils.lang("staff_chat_prefix")),
    DEVCHAT(MessengerUtils.lang("dev_chat")),
    DEVCHAT_PREFIX(MessengerUtils.lang("dev_chat_prefix")),
    BUILDERCHAT(MessengerUtils.lang("build_chat")),
    BUILDERCHAT_PREFIX(MessengerUtils.lang("build_chat_prefix")),
    MODOCHAT(MessengerUtils.lang("modo_chat")),
    MODOCHAT_PREFIX(MessengerUtils.lang("modo_chat_prefix")),
    NO_CONSOLE_COMMAND(MessengerUtils.lang("no_console_cmd")),
    NO_CONSOLE_COMMAND_WITHOUT_ARGS(MessengerUtils.lang("no_console_cmd_without_args")),
    NOT_A_PLAYER(MessengerUtils.lang("not_a_player")),
    CMD_NO_PERM(MessengerUtils.lang("no_perm")),
    CMD_NO_PERM_TO_OTHER(MessengerUtils.lang("no_perm_to_other")),
    CMD_NO_ARGS(MessengerUtils.lang("no_args")),
    CMD_INVALID_ARGS(MessengerUtils.lang("cmd_invalid_args")),
    CMD_ERROR(MessengerUtils.lang("cmd_error")),
    CMD_ERROR_ASSISTANCE(MessengerUtils.lang("cmd_error_assistance")),
    CMD_ERROR_SUGGEST(MessengerUtils.lang("cmd_error_suggest")),
    ACTIONBAR_SENT_TO_OTHER(MessengerUtils.lang("actionbosstitle_sent_to_other")),
    ACTIONBAR_SENT_TO_ALL(MessengerUtils.lang("actionbosstitle_sent_to_all")),
    AFK_BROADCAST_ENABLED(MessengerUtils.lang("afk_enabled_broadcast")),
    AFK_ENABLED(MessengerUtils.lang("afk_enabled_self")),
    AFK_BROADCAST_DISABLED(MessengerUtils.lang("afk_disabled_broadcast")),
    AFK_DISABLED(MessengerUtils.lang("afk_disabled_self")),
    ALERT_PREFIX(MessengerUtils.lang("alert_prefix")),
    ALERT_CMD(MessengerUtils.lang("alert_sent")),
    BAN_ADMIN(MessengerUtils.lang("ban_admin")),
    BAN_ALERT(MessengerUtils.lang("ban_alert")),
    BAN_DONE(MessengerUtils.lang("ban_done")),
    BAN_ERROR(MessengerUtils.lang("ban_error")),
    BAN_PREFIX(MessengerUtils.lang("ban_prefix")),
    BROADCAST_PREFIX(MessengerUtils.lang("broadcast_prefix")),
    BROADCAST_CMD(MessengerUtils.lang("broadcast_sent")),
    CHAT_FORMAT(MessengerUtils.lang("chat_format")),
    CLEARCHAT(MessengerUtils.lang("clear_chat")),
    CLEARINV_SELF_DONE(MessengerUtils.lang("clear_self")),
    CLEARINV_ADMIN(MessengerUtils.lang("clear_by_admin")),
    CLEARINV_SENDER(MessengerUtils.lang("clear_admin")),
    COMPASS_LOC(MessengerUtils.lang("compass_loc")),
    ECONOMY_BALANCE(MessengerUtils.lang("economy_balance")),
    ECONOMY_BANK_BALANCE(MessengerUtils.lang("economy_bank_balance")),
    ECONOMY_BANK_CREATED(MessengerUtils.lang("economy_bank_created")),
    ECONOMY_BANK_DEPOSIT(MessengerUtils.lang("economy_bank_deposit")),
    ECONOMY_BANK_RESET(MessengerUtils.lang("economy_bank_reset")),
    ECONOMY_BANK_WITHDRAW(MessengerUtils.lang("economy_bank_withdraw")),
    ECONOMY_BALANCE_OTHER(MessengerUtils.lang("economy_balance_other")),
    ECONOMY_PAY_SENT(MessengerUtils.lang("economy_pay_sender")),
    ECONOMY_PAY_OTHER(MessengerUtils.lang("economy_pay_receiver")),
    ECONOMY_DEPOSIT(MessengerUtils.lang("economy_gave")),
    ECONOMY_WITHDRAW(MessengerUtils.lang("economy_withdraw")),
    ECONOMY_RESET(MessengerUtils.lang("economy_reset")),
    ECONOMY_SET(MessengerUtils.lang("economy_set")),
    ENDERCHEST_ADMIN_OPEN(MessengerUtils.lang("enderchest_opened_by_admin")),
    FEED_SELF(MessengerUtils.lang("feed_self_done")),
    FEED_OTHER_SENDER(MessengerUtils.lang("feed_admin")),
    FEED_OTHER(MessengerUtils.lang("feed_by_admin")),
    FEED_ALREADY(MessengerUtils.lang("feed_self_already")),
    FEED_ALREADY_SENDER(MessengerUtils.lang("feed_admin_already")),
    FLY_TOGGLE_ON(MessengerUtils.lang("fly_enabled_self")),
    FLY_TOGGLE_OFF(MessengerUtils.lang("fly_disabled_self")),
    FLY_TOGGLE_ON_BY_ADMIN(MessengerUtils.lang("fly_enabled_by_admin")),
    FLY_TOGGLE_OFF_BY_ADMIN(MessengerUtils.lang("fly_disabled_by_admin")),
    FLY_TOGGLE_ON_SENDER(MessengerUtils.lang("fly_enabled_admin")),
    FLY_TOGGLE_OFF_SENDER(MessengerUtils.lang("fly_disabled_admin")),
    FREEZE_TOGGLE_ON(MessengerUtils.lang("freeze_enabled_by_admin")),
    FREEZE_TOGGLE_OFF(MessengerUtils.lang("freeze_disabled_by_admin")),
    FREEZE_TOGGLE_ON_ADMIN(MessengerUtils.lang("freeze_enabled_admin")),
    FREEZE_TOGGLE_OFF_ADMIN(MessengerUtils.lang("freeze_disabled_admin")),
    FREEZE_BREAK(MessengerUtils.lang("freeze_break_block")),
    FREEZE_CHAT(MessengerUtils.lang("freeze_chat")),
    FREEZE_DROP(MessengerUtils.lang("freeze_drop_item")),
    FREEZE_MOVE(MessengerUtils.lang("freeze_move")),
    FREEZE_PICKUP(MessengerUtils.lang("freeze_pickup_item")),
    FREEZE_PLACE(MessengerUtils.lang("freeze_place")),
    FURNACE_ERROR(MessengerUtils.lang("furnace_error")),
    FURNACE_DONE(MessengerUtils.lang("furnace_done")),
    GAMEMODE_SELF(MessengerUtils.lang("gamemode_self")),
    GAMEMODE_OTHER(MessengerUtils.lang("gamemode_by_admin")),
    GAMEMODE_OTHER_ADMIN(MessengerUtils.lang("gamemode_admin")),
    GIVE_DONE(MessengerUtils.lang("give_done")),
    GIVE_ERROR(MessengerUtils.lang("give_error")),
    GOD_SELF_ON(MessengerUtils.lang("god_enabled_self")),
    GOD_SELF_OFF(MessengerUtils.lang("god_disabled_self")),
    GOD_OTHER_ON(MessengerUtils.lang("god_enabled_by_admin")),
    GOD_OTHER_OFF(MessengerUtils.lang("god_disabled_by_admin")),
    GOD_OTHER_ADMIN_ON(MessengerUtils.lang("god_enabled_admin")),
    GOD_OTHER_ADMIN_OFF(MessengerUtils.lang("god_disabled_admin")),
    HELPOP_FORMAT(MessengerUtils.lang("helpop_format")),
    HELPOP_DONE(MessengerUtils.lang("helpop_sent")),
    HELPOP_NO_ADMINS(MessengerUtils.lang("helpop_no_admins")),
    HEAL_SELF(MessengerUtils.lang("heal_self")),
    HEAL_OTHER(MessengerUtils.lang("heal_by_admin")),
    HEAL_OTHER_SENDER(MessengerUtils.lang("heal_admin")),
    HEAL_ALREADY(MessengerUtils.lang("heal_self_already")),
    HEAL_ALREADY_SENDER(MessengerUtils.lang("heal_admin_already")),
    INVSEE_ADMIN(MessengerUtils.lang("invsee_admin")),
    KICK_ALERT(MessengerUtils.lang("kick_broadcast")),
    KICK_PREFIX(MessengerUtils.lang("kick_prefix")),
    KILL_DONE(MessengerUtils.lang("kill_done")),
    LEVEL_ADD(MessengerUtils.lang("level_add")),
    LEVEL_SET(MessengerUtils.lang("level_set")),
    LEVEL_REMOVE(MessengerUtils.lang("level_remove")),
    LEVEL_ADD_OTHER(MessengerUtils.lang("level_add_other")),
    LEVEL_SET_OTHER(MessengerUtils.lang("level_set_other")),
    LEVEL_REMOVE_OTHER(MessengerUtils.lang("level_remove_other")),
    LIST(MessengerUtils.lang("list")),
    LIST_HOVER(MessengerUtils.lang("list_hover")),
    MUTE_CHAT(MessengerUtils.lang("mute_chat")),
    MUTE_ENABLED(MessengerUtils.lang("mute_enabled")),
    MUTE_ENABLED_REASON(MessengerUtils.lang("mute_enabled_reason")),
    MUTE_DISABLED(MessengerUtils.lang("mute_disabled")),
    MUTE_ENABLED_ADMIN(MessengerUtils.lang("mute_enabled_admin")),
    MUTE_ENABLED_REASON_ADMIN(MessengerUtils.lang("mute_enabled_reason_admin")),
    MUTE_DISABLED_ADMIN(MessengerUtils.lang("mute_disabled_admin")),
    MULTIINFOS_MSG(
            "<green><strikethrough>-+------------+-<gray></strikethrough> - <yellow><bold>{ <gold>%plname%<gray> - <dark_gray>[<light_purple>infos<dark_gray>] <yellow><bold>} <gray>- <green><strikethrough>-+-----------+-</strikethrough>" +
            "\n <gray>- <gold>/multihelp <gray>=>" + HELP_MULTICOMMANDS.getMessage() +
            "\n<yellow>Name<dark_gray>: <gold>%plname%" +
            "\n<aqua>Author<dark_gray>: <dark_aqua>%author%" +
            "\n<green>Version<dark_gray>: <yellow>%version%" +
            "\n<blue>Description<dark_gray>: <aqua>%description%" +
            "\n<green><strikethrough>-+---------------------------------------------------------+-"),
    NICKNAME_DONE(MessengerUtils.lang("nickname_done")),
    PING_SELF_MSG(MessengerUtils.lang("ping_self")),
    PING_OTHER_MSG(MessengerUtils.lang("ping_other")),
    PLUGIN_RELOADED(MessengerUtils.lang("reload")),
    SETSPAWN_DONE(MessengerUtils.lang("setspawn_done")),
    SPAWN_DONE(MessengerUtils.lang("spawn_teleport")),
    SPAWN_ERROR(MessengerUtils.lang("spawn_error")),
    TELEPORT_ERROR(MessengerUtils.lang("teleport_error")),
    TELEPORT_SELF_TO_PLAYER(MessengerUtils.lang("teleport_self_to_player")),
    TELEPORT_OTHER_TO_OTHER(MessengerUtils.lang("teleport_player_to_player_by_admin")),
    TELEPORT_OTHER_TO_OTHER_SENDER(MessengerUtils.lang("teleport_player_to_player")),
    TELEPORT_INVALID_COORDINATES(MessengerUtils.lang("teleport_error_coordinates")),
    TELEPORT_OTHER_INVALID_COORDINATES(MessengerUtils.lang("teleport_error_player_coordinates")),
    TELEPORT_SELF_TO_COORDINATES(MessengerUtils.lang("teleport_self_to_coordinates")),
    TELEPORT_OTHER_TO_COORDINATES(MessengerUtils.lang("teleport_player_to_coordinates_by_admin")),
    TELEPORT_OTHER_TO_COORDINATES_SENDER(MessengerUtils.lang("teleport_player_to_coordinates")),
    TITLE_SENT_TO_OTHER(MessengerUtils.lang("title_sent_to_player")),
    TITLE_SENT_TO_ALL(MessengerUtils.lang("title_sent_to_all")),
    TPA_ACCEPT(MessengerUtils.lang("tpa_accept")),
    TPA_ACCEPT_HOVER(MessengerUtils.lang("tpa_accept_hover")),
    TPA_DENY(MessengerUtils.lang("tpa_deny")),
    TPA_DENY_HOVER(MessengerUtils.lang("tpa_deny_hover")),
    TPA_ERROR(MessengerUtils.lang("tpa_error")),
    TPA_NO_REQUEST(MessengerUtils.lang("tpa_no_request")),
    TPA_SEND_REQUEST(MessengerUtils.lang("tpa_send_request")),
    TPA_REQUEST_ACCEPT(MessengerUtils.lang("tpa_request_accept")),
    TPA_REQUEST_DENY(MessengerUtils.lang("tpa_request_deny")),
    TPA_RECEIVED_REQUEST(MessengerUtils.lang("tpa_received_request")),
    UNBAN_DONE(MessengerUtils.lang("unban_done")),
    UNBAN_ERROR(MessengerUtils.lang("unban_error")),
    UNBAN_BROADCAST(MessengerUtils.lang("unban_broadcast")),
    VANISH_ENABLED_SELF(MessengerUtils.lang("vanish_enabled_self")),
    VANISH_DISABLED_SELF(MessengerUtils.lang("vanish_disabled_self")),
    VANISH_ENABLED_ADMIN(MessengerUtils.lang("vanish_enabled_admin")),
    VANISH_DISABLED_ADMIN(MessengerUtils.lang("vanish_disabled_admin")),
    VANISH_ENABLED_OTHER(MessengerUtils.lang("vanish_enabled_by_admin")),
    VANISH_DISABLED_OTHER(MessengerUtils.lang("vanish_disabled_by_admin")),
    ONJOIN(MessengerUtils.lang("join_message")),
    ONLEAVE(MessengerUtils.lang("leave_message")),
    ONDEATH(MessengerUtils.lang("death_message")),
    DEATHBYKILLER(MessengerUtils.lang("death_by_player")),
    DEATHLOC(MessengerUtils.lang("death_message_loc")),


;
    private final String msg;

    /**
     * The Messenger function is a static method that returns an instance of the Messenger class.
     * The function takes in a String parameter and uses it to create an instance of the Messenger class.
     *
     *
     * @param msg Set the message of the object
     */
    Messenger(String msg) {
        this.msg = msg;
    }

    /**
     * The getMessage function returns the message of the exception.
     *
     *
     *
     * @return The message
     */
    public String getMessage() {
        return this.msg;
    }
}
