package me.capitainecat0.multicommands.utils;

import static me.capitainecat0.multicommands.utils.MessengerUtils.*;

public enum Messenger {
    HELP_AFK(MessengerUtils.lang("help_afk")),
    HELP_ALERT(MessengerUtils.lang("help_alert")),
    HELP_BAN(MessengerUtils.lang("help_ban")),
    HELP_BROADCAST(MessengerUtils.lang("help_broadcast")),
    HELP_CLEARINV(MessengerUtils.lang("help_clear")),
    HELP_CRAFT(MessengerUtils.lang("help_craft")),
    HELP_ECONOMY(MessengerUtils.lang("help_economy")),
    HELP_ENDERCHEST(MessengerUtils.lang("help_enderchest")),
    HELP_FEED(MessengerUtils.lang("help_feed")),
    HELP_FLY(MessengerUtils.lang("help_fly")),
    HELP_FREEZE(MessengerUtils.lang("help_freeze")),
    HELP_FURNACE(MessengerUtils.lang("help_furnace")),
    HELP_GAMEMODE(MessengerUtils.lang("help_gamemode")),
    HELP_GOD(MessengerUtils.lang("help_god")),
    HELP_HEAL(MessengerUtils.lang("help_heal")),
    HELP_HELPOP(MessengerUtils.lang("help_helpop")),
    HELP_INVSEE(MessengerUtils.lang("help_invsee")),
    HELP_KICK(MessengerUtils.lang("help_kick")),
    HELP_LIST(MessengerUtils.lang("help_list")),
    HELP_MULTIINFOS(MessengerUtils.lang("help_multiinfos")),
    HELP_NICK(MessengerUtils.lang("help_nick")),
    HELP_PING(MessengerUtils.lang("help_ping")),
    HELP_PLUGINS(MessengerUtils.lang("help_plugins")),
    HELP_RELOAD(MessengerUtils.lang("help_reload")),
    HELP_SETSPAWN(MessengerUtils.lang("help_setspawn")),
    HELP_SPAWN(MessengerUtils.lang("help_spawn")),
    HELP_SERVERINFO(MessengerUtils.lang("help_serverinfo")),
    HELP_TELEPORT(MessengerUtils.lang("help_teleport")),
    HELP_VANISH(MessengerUtils.lang("help_vanish")),
    HELP_WHOIS(MessengerUtils.lang("help_whois")),
    ADMINCHAT(MessengerUtils.lang("admin_chat")),
    ADMINCHAT_PREFIX(MessengerUtils.lang("admin_chat_prefix")),
    STAFFCHAT(MessengerUtils.lang("staff_chat")),
    STAFFCHAT_PREFIX(MessengerUtils.lang("staff_chat_prefix")),
    DEVCHAT(MessengerUtils.lang("dev_chat")),
    DEVCHAT_PREFIX(MessengerUtils.lang("dev_chat_prefix")),
    BUILDERCHAT(MessengerUtils.lang("build_chat")),
    BUILDERCHAT_PREFIX(MessengerUtils.lang("build_chat_prefix")),
    MODOCHAT(MessengerUtils.lang("modo_chat")),
    MODOCHAT_PREFIX(MessengerUtils.lang("modo_chat_prefix")),
    NO_CONSOLE_COMMAND(MessengerUtils.lang("no_console_cmd")),
    NO_CONSOLE_COMMAND_WITHOUT_ARGS(MessengerUtils.lang("no_console_cmd_without_args")),
    NOT_A_PLAYER(MessengerUtils.lang("not_a_player")),
    CMD_NO_PERM(MessengerUtils.lang("no_perm")),
    CMD_NO_PERM_TO_OTHER(MessengerUtils.lang("no_perm_to_other")),
    CMD_NO_ARGS(MessengerUtils.lang("no_args")),
    ACTIONBAR_SENT_TO_OTHER(MessengerUtils.lang("actionbosstitle_sent_to_other")),
    ACTIONBAR_SENT_TO_ALL(MessengerUtils.lang("actionbosstitle_sent_to_all")),
    AFK_BROADCAST_ENABLED(colored(MessengerUtils.lang("afk_enabled_broadcast"))),
    AFK_ENABLED(MessengerUtils.lang("afk_enabled_self")),
    AFK_BROADCAST_DISABLED(colored(MessengerUtils.lang("afk_disabled_broadcast"))),
    AFK_DISABLED(MessengerUtils.lang("afk_disabled_self")),
    ALERT_PREFIX(MessengerUtils.lang("alert_prefix")),
    ALERT_CMD(MessengerUtils.lang("alert_sent")),
    BAN_PREFIX(MessengerUtils.lang("ban_prefix")),
    BROADCAST_PREFIX(MessengerUtils.lang("broadcast_prefix")),
    BROADCAST_CMD(MessengerUtils.lang("broadcast_sent")),
    CLEARINV_SELF_DONE(MessengerUtils.lang("clear_self")),
    CLEARINV_ADMIN(MessengerUtils.lang("clear_by_admin")),
    CLEARINV_SENDER(MessengerUtils.lang("clear_admin")),
    COMPASS_LOC(MessengerUtils.lang("compass_loc")),
    ECONOMY_BALANCE(MessengerUtils.lang("economy_balance")),
    ECONOMY_BANK_BALANCE(MessengerUtils.lang("economy_bank_balance")),
    ECONOMY_BANK_CREATED(MessengerUtils.lang("economy_bank_created")),
    ECONOMY_BANK_DEPOSIT(MessengerUtils.lang("economy_bank_deposit")),
    ECONOMY_BANK_RESET(MessengerUtils.lang("economy_bank_reset")),
    ECONOMY_BANK_WITHDRAW(MessengerUtils.lang("economy_bank_withdraw")),
    ECONOMY_BALANCE_OTHER(MessengerUtils.lang("economy_balance_other")),
    ECONOMY_PAY_SENT(MessengerUtils.lang("economy_pay_sender")),
    ECONOMY_PAY_OTHER(MessengerUtils.lang("economy_pay_receiver")),
    ECONOMY_DEPOSIT(MessengerUtils.lang("economy_gave")),
    ECONOMY_WITHDRAW(MessengerUtils.lang("economy_withdraw")),
    ECONOMY_RESET(MessengerUtils.lang("economy_reset")),
    ECONOMY_SET(MessengerUtils.lang("economy_set")),
    ENDERCHEST_ADMIN_OPEN(MessengerUtils.lang("enderchest_opened_by_admin")),
    FEED_SELF(MessengerUtils.lang("feed_self_done")),
    FEED_OTHER_SENDER(MessengerUtils.lang("feed_admin")),
    FEED_OTHER(MessengerUtils.lang("feed_by_admin")),
    FEED_ALREADY(MessengerUtils.lang("feed_self_already")),
    FEED_ALREADY_SENDER(MessengerUtils.lang("feed_admin_already")),
    FLY_TOGGLE_ON(MessengerUtils.lang("fly_enabled_self")),
    FLY_TOGGLE_OFF(MessengerUtils.lang("fly_disabled_self")),
    FLY_TOGGLE_ON_BY_ADMIN(MessengerUtils.lang("fly_enabled_by_admin")),
    FLY_TOGGLE_OFF_BY_ADMIN(MessengerUtils.lang("fly_disabled_by_admin")),
    FLY_TOGGLE_ON_SENDER(MessengerUtils.lang("fly_enabled_admin")),
    FLY_TOGGLE_OFF_SENDER(MessengerUtils.lang("fly_disabled_admin")),
    FREEZE_TOGGLE_ON(MessengerUtils.lang("freeze_enabled_by_admin")),
    FREEZE_TOGGLE_OFF(MessengerUtils.lang("freeze_disabled_by_admin")),
    FREEZE_TOGGLE_ON_ADMIN(MessengerUtils.lang("freeze_enabled_admin")),
    FREEZE_TOGGLE_OFF_ADMIN(MessengerUtils.lang("freeze_disabled_admin")),
    FREEZE_BREAK(MessengerUtils.lang("freeze_break_block")),
    FREEZE_CHAT(MessengerUtils.lang("freeze_chat")),
    FREEZE_DROP(MessengerUtils.lang("freeze_drop_item")),
    FREEZE_MOVE(MessengerUtils.lang("freeze_move")),
    FREEZE_PICKUP(MessengerUtils.lang("freeze_pickup_item")),
    FREEZE_PLACE(MessengerUtils.lang("freeze_place")),
    FURNACE_ERROR(MessengerUtils.lang("furnace_error")),
    FURNACE_DONE(MessengerUtils.lang("furnace_done")),
    GAMEMODE_SELF(MessengerUtils.lang("gamemode_self")),
    GAMEMODE_OTHER(MessengerUtils.lang("gamemode_by_admin")),
    GAMEMODE_OTHER_ADMIN(MessengerUtils.lang("gamemode_admin")),
    GIVE_DONE(MessengerUtils.lang("give_done")),
    GIVE_ERROR(MessengerUtils.lang("give_error")),
    GOD_SELF_ON(MessengerUtils.lang("god_enabled_self")),
    GOD_SELF_OFF(MessengerUtils.lang("god_disabled_self")),
    GOD_OTHER_ON(MessengerUtils.lang("god_enabled_by_admin")),
    GOD_OTHER_OFF(MessengerUtils.lang("god_disabled_by_admin")),
    GOD_OTHER_ADMIN_ON(MessengerUtils.lang("god_enabled_admin")),
    GOD_OTHER_ADMIN_OFF(MessengerUtils.lang("god_disabled_admin")),
    HELPOP_FORMAT(MessengerUtils.lang("helpop_format")),
    HELPOP_DONE(MessengerUtils.lang("helpop_sent")),
    HELPOP_NO_ADMINS(MessengerUtils.lang("helpop_no_admins")),
    HEAL_SELF(MessengerUtils.lang("heal_self")),
    HEAL_OTHER(MessengerUtils.lang("heal_by_admin")),
    HEAL_OTHER_SENDER(MessengerUtils.lang("heal_admin")),
    HEAL_ALREADY(MessengerUtils.lang("heal_self_already")),
    HEAL_ALREADY_SENDER(MessengerUtils.lang("heal_admin_already")),
    INVSEE_ADMIN(MessengerUtils.lang("invsee_admin")),
    KICK_PREFIX(MessengerUtils.lang("kick_prefix")),
    LIST(MessengerUtils.lang("list")),
    LIST_HOVER(MessengerUtils.lang("list_hover")),
    MULTIINFOS_MSG(colored(
            "&a&m-+------------+-&7 - &e&l{ &6%plname%&7 - &2[&dinfos&2] &e&l} &7- &a&m-+-----------+-" +
            "\n &7- &6/multihelp &7=> Vous permet d'afficher l'aide des plugins de la série Multi" +
            "\n&eNom&8: &6%plname%" +
            "\n&bAuteur&8: &3%author%" +
            "\n&aVersion&8: &e%version%" +
            "\n&9Description&8: &b%description%" +
            "\n&a&m-+---------------------------------------------------------+-")),
    NICKNAME_DONE(MessengerUtils.lang("nickname_done")),
    PING_SELF_MSG(MessengerUtils.lang("ping_self")),
    PING_OTHER_MSG(MessengerUtils.lang("ping_other")),
    PLUGIN_RELOADED(MessengerUtils.lang("reload")),
    SETSPAWN_DONE(MessengerUtils.lang("setspawn_done")),
    SPAWN_DONE(MessengerUtils.lang("spawn_teleport")),
    SPAWN_ERROR(MessengerUtils.lang("spawn_error")),
    TELEPORT_ERROR(MessengerUtils.lang("teleport_error")),
    TELEPORT_SELF_TO_PLAYER(MessengerUtils.lang("teleport_self_to_player")),
    TELEPORT_OTHER_TO_OTHER(MessengerUtils.lang("teleport_player_to_player_by_admin")),
    TELEPORT_OTHER_TO_OTHER_SENDER(MessengerUtils.lang("teleport_player_to_player")),
    TELEPORT_INVALID_COORDINATES(MessengerUtils.lang("teleport_error_coordinates")),
    TELEPORT_OTHER_INVALID_COORDINATES(MessengerUtils.lang("teleport_error_player_coordinates")),
    TELEPORT_SELF_TO_COORDINATES(MessengerUtils.lang("teleport_self_to_coordinates")),
    TELEPORT_OTHER_TO_COORDINATES(MessengerUtils.lang("teleport_player_to_coordinates_by_admin")),
    TELEPORT_OTHER_TO_COORDINATES_SENDER(MessengerUtils.lang("teleport_player_to_coordinates")),
    VANISH_ENABLED_SELF(MessengerUtils.lang("vanish_enabled_self")),
    VANISH_DISABLED_SELF(MessengerUtils.lang("vanish_disabled_self")),
    VANISH_ENABLED_ADMIN(MessengerUtils.lang("vanish_enabled_admin")),
    VANISH_DISABLED_ADMIN(MessengerUtils.lang("vanish_disabled_admin")),
    VANISH_ENABLED_OTHER(MessengerUtils.lang("vanish_enabled_by_admin")),
    VANISH_DISABLED_OTHER(MessengerUtils.lang("vanish_disabled_by_admin")),
    ONJOIN(MessengerUtils.lang("join_message")),
    ONLEAVE(MessengerUtils.lang("leave_message")),
    ONDEATH(MessengerUtils.lang("death_message")),
    DEATHLOC(MessengerUtils.lang("death_message_loc"));

    private final String msg;

    private Messenger(String msg) {
        this.msg = msg;
    }

    public String getMessage() {
        return this.msg;
    }
}
