#Configuration file of MultiCommands

#Les messages peuvent êtres envoyés de plusieurs façons :
# - ACTIONBAR | actionbar
# - CHAT | chat
# - TITLE | title
# - BOSSBAR | bossbar
send-message-on: ACTIONBAR

#Activer et gérer les effets sonores:
#Liste des effets sonores de Minecraft
#https://www.digminecraft.com/lists/sound_list_pc.php

enable-command-sounds: true

console-setup: true

#Pas de permissions / Erreurs en tous genres :
no-perm-sound: "BLOCK_ANVIL_PLACE"

#Commande effectuée:
cmd-done-sound: "ENTITY_EXPERIENCE_ORB_PICKUP"

#Sons custom:
feed-heal-sounds: true

#Activer / désactiver le GUI d'aide
enable-help-gui: true

#Valeurs max en bloc que la commande prend en compte
#pour les coordonées X et Z
random-teleporter-max-X: 25000
random-teleporter-max-Z: 25000

#Ne pas changer ces valeurs, sauf si vous savez ce que vous faites
spawn:
