#Fichier de configuration du plugin MultiCommands

#Changer la langue du plugin :
lang: en

#Les messages peuvent être envoyés dans différents canaux :
# - ACTIONBAR | actionbar
# - CHAT | chat
# - TITLE | title
# - BOSSBAR | bossbar
send-message-on: ACTIONBAR

#Gérer les effets sonores :
#Liste des sons :
#https://www.digminecraft.com/lists/sound_list_pc.php

enable-command-sounds: true

#Activer ou non les messages de démarrage:
console-setup: true

#Sons d'erreurs:
no-perm-sound: "BLOCK_ANVIL_PLACE"

#Sons de succès:
cmd-done-sound: "ENTITY_EXPERIENCE_ORB_PICKUP"

#Sons custom:
feed-heal-sounds: true

#Activer ou désactiver le HelpGUI :
#(désactivez ce paramêtre si vous n'utilisez pas de Build paperSpigot)
enable-help-gui: true

#Valeures max des coordonées X et Z pour la commande /rtp :
random-teleporter-max-X: 25000
random-teleporter-max-Z: 25000

#/!\ NE PAS TOUCHER /!\
#Paramêtre vide par défaut,
#se remplis grâce à la commande /setspawn#(si vous modifiez ces paramères,
#la commande pourrait ne pas fonctionner)
spawn:
